### ISSUE TITLE
Multiple "DB Error"s after installation

### ISSUE THREAD

**Issue by 7adietri** [blind-coder/rcmcarddav#172]
After installing carddav via composer and trying to login, this appears:

    DATABASE ERROR: CONNECTION FAILED!
    Unable to connect to the database!
    Please contact your server-administrator.

The error log contains this:

    [20-Nov-2016 17:45:22 +0100]: <na1dfa0f> DB Error: [1146] Table 'roundcube.carddav_migrations' doesn't exist (SQL Query: SELECT * FROM carddav_migrations WHERE filename IN ('0000-dbinit','0000-sample','0001-categories','0002-increasetextfieldlengths')) in /srv/example.com/roundcubemail/program/lib/roundcubemail/rcube_db.php on line 539 (POST /roundcubemail/?_task=login&_action=login)
    [20-Nov-2016 17:45:22 +0100]: <na1dfa0f> DB Error: [1067] Invalid default value for 'last_updated' (SQL Query: -- table to store the configured address books
    CREATE TABLE IF NOT EXISTS carddav_addressbooks (
      id INT UNSIGNED NOT NULL AUTO_INCREMENT,
      name VARCHAR(64) NOT NULL,
      username VARCHAR(64) NOT NULL,
      password VARCHAR(255) NOT NULL,
      url VARCHAR(255) NOT NULL,
      active TINYINT UNSIGNED NOT NULL DEFAULT 1,
      user_id INT(10) UNSIGNED NOT NULL,
      last_updated TIMESTAMP NOT NULL DEFAULT 0, -- time stamp of the last update of the local database
      refresh_time TIME NOT NULL DEFAULT '01:00:00', -- time span after that the local database will be refreshed, default 1h
      sync_token VARCHAR(255) NOT NULL DEFAULT '', -- sync-token the server sent us for the last sync
      authentication_scheme VARCHAR(64) NOT NULL DEFAULT "auto", -- the HTTP authentication scheme to use, auto will be overwritten
  
      presetname   VARCHAR(64), -- presetname
  
      PRIMARY KEY(id),
      FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
    ) CHARACTER SET utf8 COLLATE utf8_unicode_ci /*!40000 ENGINE=INNODB */) in /srv/example.com/roundcubemail/program/lib/roundcubemail/rcube_db.php on line 539 (POST /roundcubemail/?_task=login&_action=login)
    [20-Nov-2016 17:45:23 +0100]: <na1dfa0f> DB Error: [1215] Cannot add foreign key constraint (SQL Query: CREATE TABLE IF NOT EXISTS carddav_contacts (
      id INT UNSIGNED NOT NULL AUTO_INCREMENT,
      abook_id INT UNSIGNED NOT NULL,
      name VARCHAR(255)     NOT NULL, -- display name
      email VARCHAR(255), -- ", " separated list of mail addresses
      firstname VARCHAR(255),
      surname VARCHAR(255),
      organization VARCHAR(255),
      showas VARCHAR(32) NOT NULL DEFAULT '', -- special display type (e.g., as a company)
      vcard LONGTEXT NOT NULL, -- complete vcard
      etag VARCHAR(255) NOT NULL, -- entity tag, can be used to check if card changed on server
      uri  VARCHAR(255) NOT NULL, -- path of the card on the server
      cuid VARCHAR(255) NOT NULL, -- unique identifier of the card within the collection
  
      PRIMARY KEY(id),
      INDEX (abook_id),
      UNIQUE INDEX(uri,abook_id),
      UNIQUE INDEX(cuid,abook_id),
      FOREIGN KEY (abook_id) REFERENCES carddav_addressbooks(id) ON DELETE CASCADE ON UPDATE CASCADE
    ) CHARACTER SET utf8 COLLATE utf8_unicode_ci /*!40000 ENGINE=INNODB */) in /srv/example.com/roundcubemail/program/lib/roundcubemail/rcube_db.php on line 539 (POST /roundcubemail/?_task=login&_action=login)

The last error message ("Cannot add foreign key constraint") appears for multiple tables.

I have installed Roundcube 1.2.2 on PHP 7.0.8 and MySQL 5.7.16.

**Comment by blind-coder** [comment]
You need to fix the database connection first. As RCMCardDAV uses Roundcubes built-in database routines, there's nothing RCMCardDAV can do if Roundcube can't access its database.

**Comment by 7adietri** [comment]
Roundcube has no problem accessing the DB, this appears only after installing carddav.

My guess is there's a problem with the SQL statements ("Invalid default value" sounds pretty bad), but I'm not fluent in this area.

**Comment by blind-coder** [comment]
Aaah, I didn't see that.
Please try the latest version of RCMCardDAV (2.0.2) which addresses exactly the issue with the default value.

**Comment by 7adietri** [comment]
What do I put in the composer.json? Right now I have `dev-master` in there and the installed version is 2.0.0, according to the package.xml.

**Comment by blind-coder** [comment]
Just use ``2.0.*`` and it should get the latest 2.0.* release.

**Comment by 7adietri** [comment]
Just tried it, now composer seems unhappy:

    Updating dependencies (including require-dev)                  
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - The requested package roundcube/carddav 2.0.* exists as roundcube/carddav[dev-feature_composer, dev-issue_129, dev-issue_46, dev-issue_54, dev-master, dev-migfieldlength, dev-pr_6, dev-release-2.0, dev-skrat-photocrop] but these are rejected by your constraint.

Unfortunately, I'm not sure what it means by "your constraint".

**Comment by blind-coder** [comment]
Okay, apparently I still don't really understand composer... 

If you put as version "dev-release-2.0" that should finally do it.

**Comment by 7adietri** [comment]
Sorry, that only brought me up to version 2.0.1.

Maybe I should try a different installation method?

**Comment by 7adietri** [comment]
Ok, I installed version 2.0.2 (according to the package.xml) via git, but unfortunately it still complains about "Invalid default value" (the default value seems to be "1970-01-01 00:00:01" now), followed by a lot of "Cannot add foreign key constraint".

**Comment by mokas01** [comment]
Hi, 

I got pretty much the same problem, running php 5.6.27 and mysql 5.5.53 and the last version of the plugin.
`DB Error: [1146] Table 'roundcube.carddav_migrations' doesn't exist (SQL Query: SELECT * FROM carddav_migrations WHERE filename IN ('0000-dbinit','0000-sample','0001-categories','0002-increasetextfieldlengths','0003-fixtimestampdefaultvalue')) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 539 (GET /)
`
the rest is [on this pastebin](http://paste.yunohost.org/lugupakiwi.vbs)

then other errors come in raw as it seems it tries to write in not-created databases. I checked, the databases haven't been created. I don't know if it changes anything but my roundcube instance came with preinstalled with automatic_addressbook plugin (i tryed not to load it but it didn't help)

Thanks in advance for the help

**Comment by blind-coder** [comment]
Am 24. November 2016 17:45:20 MEZ, schrieb mokas01 <notifications@github.com>:
>Hi, 
>
>I got pretty much the same problem, running php 5.6.27 and mysql 5.5.53
>and the last version of the plugin.
>`DB Error: [1146] Table 'roundcube.carddav_migrations' doesn't exist
>(SQL Query: SELECT * FROM carddav_migrations WHERE filename IN
>('0000-dbinit','0000-sample','0001-categories','0002-increasetextfieldlengths','0003-fixtimestampdefaultvalue'))
>in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 539
>(GET /)
>`
>the rest is [on this
>pastebin](http://paste.yunohost.org/lugupakiwi.vbs)
>
>then other errors come in raw as it seems it tries to write in
>not-created databases. I checked, the databases haven't been created. I
>don't know if it changes anything but my roundcube instance came with
>preinstalled with automatic_addressbook plugin (i tryed not to load it
>but it didn't help)
>
>Thanks in advance for the help
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/172#issuecomment-262815502

God, I hate time/date stuff. I'll take care of this asap. In the meantime, setting this to anything in the 2000s seems to do the trick.

**Comment by mokas01** [comment]
Hi, thanks for the answer.
I tryed to change the date in 0000-dbinit and to run composer again —> nothing to install or update. Do I have to run the 4 scripts manually ? Have I understood something wrong ?

**Comment by blind-coder** [comment]
Just drop the carddav tables in your database, logout of roundcube and log back in. This will run the migrations again.

**Comment by blind-coder** [comment]
I have pushed v2.0.3 which should finally address this issue. I've set the default to the year 2000 which shouldn't clash with timezone constraints while still updating the addressbook immediately after creation.

**Comment by mokas01** [comment]
Hi,
Thanks for the update. It changed something but it is unfortunately not working yet. [Here](http://paste.yunohost.org/raw/gepiwipume) is the new error log. As I see user_id in the log, I realize I didn't tell you the user are managed with ldap, if it is of any importance.
Thanks again for the help !

**Comment by blind-coder** [comment]
And that, ladies and gentlemen, is why you don't do two things at once!
I forgot to fix 0000-dbinit, too, which I just did with v2.0.4.

Sorry for all the hassly, but could you please try again (dropping the tables, logging out, logging back in).

**Comment by mokas01** [comment]
Still not :/
I am sorry and thankful you spend so much time trying to help. This time, a single line error, on each reload of the page : 
`DB Error: [1146] Table 'roundcube.carddav_addressbooks' doesn't exist (GET /)`

Let me know if you want me to try something else !

**Comment by blind-coder** [comment]
That sounds like you didn't drop the tables, logged out of Roundcube and logged back in to trigger the migrations.

**Comment by 7adietri** [comment]
It's working! I updated to version 2.0.4, dropped the one `carddav_` DB table that got created and on the next login I was able to configure my addressbook.

Thanks Benjamin!

**Comment by mokas01** [comment]
hi !
You were right. I wasn't  properly disconnected and it is now working. Thanks a lot for the really nice and quick help !
Best
