### ISSUE TITLE
Filter contacts so that only conracts with e-mail are displayed 

### ISSUE THREAD

**Issue by thommierother** [blind-coder/rcmcarddav#181]
Hi,
I have an addressbook shared within a community which has around 350 contacts, but only about 1/3 of them have e-mail addresses. I want to display only those contacts inside roundcube as a shared (read only) address book that have an e-mail address. Is there any configuration option I did not see or any workaround for this?

**Comment by blind-coder** [comment]
I honestly thought roundcube would do that itself. I'll set something up, right now, there is no optoin.

**Comment by thommierother** [comment]
The focus of the config options for the adressbook (https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php) seems to be on LDAP settings but a simple filter option to avoid search in entries which have null values is missing... Thx for an option inside rcmcarddav, I would be happy to offer some testing ...

**Comment by blind-coder** [comment]
I just tested around a bit and found that roundcube DOES that filtering (and RCMCardDAV supports it) when doing the autocompletion for message composing. That means that contacts without an email address are not displayed when composing messages, but they ARE displayed in the addressbook itself.
I assume that that is what you also want to have removed?

**Comment by blind-coder** [comment]
I have pushed branch issue_181 which implements the optional, addressbook-preset specific option "require_always" which might be exactly what you want.

**Comment by thommierother** [comment]
ok, thanks, I will try it

**Comment by thommierother** [comment]
Hey Benjamin,

I did a test with that code but maybe something went wrong.
I deleted all carddav_* tables from the roundcubbe database. Then I used
the new code with these config settings:

//// ** ADDRESSBOOK PRESETS

// Each addressbook preset takes the following form:

$prefs['oc'] = array(
        // required attributes
        'name'         =>  'Owncloud Kontakte',
        'username'     =>  'Zentrale',
        'password'     =>  '8fWzLmuxUZMv',
        'url'          => 
'https://localhost/owncloud/remote.php/dav/addressbooks/users/Zentrale/contacts/',
        // optional attributes
        'active'       =>  true,
        'readonly'     =>  true,
        'refresh_time' => '01:00:00',

        // attributes that are fixed (i.e., not editable by the user) and
        // auto-updated for this preset
        'fixed'        =>  array(),

        // hide this preset from CalDAV preferences section so users
can't even see it
        'hide' => false,
        // require values in  e-mail adress field, entries without mail
will not be requested
        'require_always' => 'email',
);

The table carddav_contacts now only has 128 entries instead of around
360 in the original dav database (See attachment) from the Oncloud
contacts module.
Maybe I didn't understand or describe it correctly. I would like to have
a display filter, not an import filter. rcmcarddav should always import
all stuff from the dav server (see URL above for testing) but only
display those that have an email address.
||
Greetings, Thommie


Am 13.02.2017 um 09:02 schrieb Benjamin Schieder:

**Comment by blind-coder** [comment]
Hey Thomas.

require_always must be an array, like so:
```php
'require_always' => ['email']
```

Apart from that, all vcard should still get imported.

**Comment by thommierother** [comment]
yep, now the filtering works. The reason why I have not all entries in
the roundcube database, must be something else, I will check that later.
But the original issue seems to be done.

Thanks & Bye,
Thommie


Am 17.02.2017 um 12:46 schrieb Benjamin Schieder:

**Comment by blind-coder** [comment]
Merged into master, will be in next release.
